-- 1. Create the 'news' table to store articles
CREATE TABLE public.news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text NOT NULL,
  content text,
  image_url text
);

-- 2. Enable Row Level Security (RLS) on the table
-- RLS is a good practice for security, especially when using public anon keys.
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow public read access to everyone
CREATE POLICY "Allow public read access" ON public.news
  FOR SELECT USING (true);

-- 4. Create a policy to allow authenticated users (admins) to insert, update, and delete
-- This assumes you are using Supabase Auth and admins will be logged in.
CREATE POLICY "Allow full access for authenticated users" ON public.news
  FOR ALL USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');

-- 5. Create a storage bucket for news images
-- Make sure to set bucket policies from the Supabase dashboard for public reads
-- and restricted writes (for authenticated users).
INSERT INTO storage.buckets (id, name, public)
  VALUES ('news_images', 'news_images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies (to be set in Supabase Dashboard UI, but here is the SQL equivalent):
-- Allow public read access to images
CREATE POLICY "Public read access for news images" ON storage.objects
  FOR SELECT USING (bucket_id = 'news_images');

-- Allow authenticated users (admins) to upload images
CREATE POLICY "Allow authenticated inserts for news images" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'news_images' AND auth.role() = 'authenticated');

-- Allow authenticated users (admins) to update/delete their own images
CREATE POLICY "Allow authenticated updates/deletes for news images" ON storage.objects
  FOR UPDATE USING (bucket_id = 'news_images' AND auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated deletes for news images" ON storage.objects
  FOR DELETE USING (bucket_id = 'news_images' AND auth.role() = 'authenticated');
